Netping/Netping_modern

NetPing_modern/Controllers/CartController.cs

[bug] Нумерация заказов с сайта может быть не уникальной

Mail sending fix

---

NetPing_modern/Content/JavaScript/blog.js
NetPing_modern/Content/Themes/blog.css

[bug] В статьях блога не правильно отображаются таблицы и искажены
пропорции на фотографиях

Blog layout

---

NetPing_modern/Controllers/ProductsController.cs

[bug] убрать отображение в каталоге устройств с меткой Archive

archive products hidden

---

NetPing_modern/Controllers/ProductsController.cs
NetPing_modern/Views/Products/Adaptive_Index.cshtml

[bug] Сделать неактивной кнопку "Купить" у товаров на новых страницах
каталога устройств, если товарам присвоен лейбл "Архив"

archive buy unavailable

---

NetPing_modern/Content/JavaScript/cart.js

[bug] При вводе количества единиц товара на новых страницах каталога с
клавиатуры, при нажатии клавиши "Enter" количество товара увеличивается
на 1

fix count increment on enter

---

NetPing_modern/Controllers/ProductsController.cs

[bug] На страницах "Датчики устройств NetPing" и "Аксессуары для
устройств NetPing" неверно указан заголовок и описание

wrong titles

---

NetPing_modern/Content/JavaScript/cart.js

[bug] при клике на кнопку Купить, должно сразу же отображаться окно
корзины

buy show cart

---

NetPing_modern/Content/JavaScript/cart.js

[bug] Нет возможности удалить единственную позицию в корзине, если окно
с корзиной отображается напротив товара

cart remove bug

---

NetPing_modern/Views/Products/Adaptive_Index.cshtml

[bug][ENG] Наименование валюты "руб.", должно быть "USD".
+
[bug] На новых страницах каталога устойств цену отображать так же, как указано в дизайне макета

price and currency

---

NetPing_modern/Content/Themes/catalog/style.css

[bug] Увеличить ширину кнопок "Купить", "Узнать больше" и "Сравнить" до
ширины, указаной в дизайне макета

buttons width fix

---

NetPing_modern/Content/Themes/adaptive-header-footer.css
NetPing_modern/Content/Themes/cart/cart.css
NetPing_modern/Content/Themes/header-footer.css
NetPing_modern/Views/Products/Compare.cshtml
NetPing_modern/Views/Products/Device_view.cshtml
NetPing_modern/Views/Products/Index.cshtml
NetPing_modern/Views/Shared/Blog_master.cshtml
NetPing_modern/Views/Shared/Header.cshtml
NetPing_modern/Views/Shared/Inner_master.cshtml

[bug] На всех страницах русскоязычного сайта сделать внешний вид корзины
аналогичный, как на новых страницах каталога устройств
+
[bug] При добавленных позициях в корзину на страницах сайта (кроме
страниц с каталогом устройств) количество добавленных товаров в шапке
сайта отображается нуль.

new cart to pages

---

NetPing_modern/Content/Themes/catalog/style.css
NetPing_modern/Views/Products/Adaptive_Index.cshtml

[bug] На страницах каталога устройств реализовать выделение области
товаров при наведении мыши, как указано в дизайне макета

device on hover fix

---

NetPing_modern/Content/Themes/adaptive-header-footer.css
NetPing_modern/Content/Themes/cart/cart.css
NetPing_modern/Resources/Views/Shared/Header.ru.resx
NetPing_modern/Views/Shared/Adaptive-Header.cshtml
NetPing_modern/obj/Debug/NetPing_modern.csproj.FileListAbsolute.txt

Обновить шапку сайта в соответствии с дизайном (бесплатная доставка)(

free delivery

---

NetPing_modern/Content/JavaScript/cart.js
NetPing_modern/Content/Themes/cart/cart.css
NetPing_modern/Controllers/CartController.cs
NetPing_modern/Views/Shared/Cart.cshtml

В форме оформления заказа убрать поля выбора доставки

free delivery cart form

---

NetPing_modern/DAL/SPOnlineRepository.cs
NetPing_modern/Resources/Camls.ru.resx
NetPing_modern/Views/Products/UserGuides.cshtml

https://netping.teamworkpm.net/tasks/3741148

---

NetPing_modern/Content/Themes/adaptive-header-footer.css
NetPing_modern/Content/Themes/catalog/style.css
NetPing_modern/Content/Themes/main.css
NetPing_modern/Controllers/ProductsController.cs
NetPing_modern/Resources/Views/Shared/Footer.ru.resx
NetPing_modern/Views/Blog/Main.cshtml
NetPing_modern/Views/Products/Adaptive_Index.cshtml
NetPing_modern/Views/Products/Compare.cshtml
NetPing_modern/Views/Shared/Adaptive-Header.cshtml
NetPing_modern/Views/Shared/Blog_master.cshtml

Bugfix 260815

---

NetPing_modern/Content/Themes/ProductPageStyle.css
NetPing_modern/Content/Themes/adaptive.css
NetPing_modern/Content/Themes/dev.css
NetPing_modern/Controllers/ProductsController.cs
NetPing_modern/Helpers/NavigationProvider.cs
NetPing_modern/Views/Products/Adaptive_Index.cshtml
NetPing_modern/Views/Products/Dev.cshtml

_[PRJ][SiteCodeUpdate] Изменение кода сайта

Bugfix prjdevprom

---

NetPing_modern/Controllers/PreorderController.cs

preorder mail to client

---

NetPing_modern/Controllers/BlogController.cs

https://netping.teamworkpm.net/tasks/4281343
Прочитать из Confluence значения PageProperties

fix https://netping.teamworkpm.net/tasks/4281343 (Прочитать из Confluence значения PageProperties)

---

NetPing_modern/App_Start/RouteConfig.cs
NetPing_modern/Content/Themes/catalog/style.css
NetPing_modern/Controllers/InnerPagesController.cs
NetPing_modern/DAL/SPOnlineRepository.cs
NetPing_modern/Models/Device.cs
NetPing_modern/NetPing_modern.csproj
NetPing_modern/Views/Products/Adaptive_Index.cshtml

https://netping.teamworkpm.net/tasklists/518951

Отображение наличия товара на складе

---

NetPing_modern/Content/Themes/catalog/style.css
NetPing_modern/Controllers/InnerPagesController.cs
NetPing_modern/DAL/SPOnlineRepository.cs
NetPing_modern/Models/Device.cs
NetPing_modern/NetPing_modern.csproj
NetPing_modern/Views/InnerPages/UCacheStock.cshtml
NetPing_modern/Views/Products/Adaptive_Index.cshtml
NetPing_modern/Views/Products/Adaptive_device_view.cshtml

На странице католога устройств в разработке не отображать наличие товара на складе

https://netping.teamworkpm.net/tasks/4350138
